baseurl = "/"
languageCode = "en-us"
title = "WHAMP"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"
contentdir = "content/post"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [statnet](https://github.com/statnet)"
